apiVersion: v1
kind: DeploymentConfig
spec:
  template:
    spec:
      serviceAccountName: sa-greeting
  triggers:
    # If we add these lines, then istio enricher will be able to include all the triggers !!!!!
    - type: ConfigChange